## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/api/*"
  to = "https://seashell-app-u77ys.ondigitalocean.app/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}